name: node ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
      - name: show list
        run: ls -a
      - name: copy dir to remote server
        uses: appleboy/scp-action@master
        with:
          host: '106.14.17.48'  
          username: 'root' 
          source: 'static/index.html'
          target: 'root'
          password: '123456Zr' 