name: node ci
on: 
  push: 
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
      - name: npm install, build
          run: |
            npm install 
            npm run build
      - name: copy dir to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.server_host }}
          username: ${{ secrets.server_userName }}
          password: ${{ secrets.server_passWrod }}
          source: ${{ secrets.source_path }}
          target: ${{ secrets.server_path }}
          